### ISSUE TITLE
DATABASE

### ISSUE THREAD

**Issue by yogesh660** [shariqfarooq123/UFCN#1]
i want to implement this project, from where i can get the database? Is there any freely available database?

**Comment by shariqfarooq123** [comment]
> i want to implement this project, from where i can get the database? Is there any freely available database?

@yogesh660 Hi Yogesh, Thanks for taking interest in the project. The data used in this project is a proprietary data of Indian Institute of Science ( IISc ) Bangalore and cannot be shared publicly. Thanks!
